config/routes.rb
Rails.application.routes.draw do
   namespace :admin do
    root "admin/users#index"
    resources :users
  end
  namespace :admin do
    root "admin/categories#index"
    resources :categories
  end

  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/rating", to: "ratings#update"

  get "/carts", to: "carts#index"
  get "/cart", to: "carts#show"
  post "/new_cart", to: "carts#create"
  post "/update_cart", to: "carts#update"
  delete "destroy_cart", to: "carts#destroy"

  resources :users
  resources :account_activations, only: :edit
  resources :ratings, only: :update
  resources :products
  resources :orders
  resources :categories
  resources :carts, only: :show
  resources :order_details, only: [:create, :update, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.get_root_categories
    @hot_products = Product.get_hot_products
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/views/static_pages/about.html.erb
<h1><%= t ".about_us" %></h1>
<p><%= t ".introduce" %></p>
<p><%= t ".luck" %></p>

app/views/static_pages/contact.html.erb
<h1><%= t ".name_page" %></h1>
<p><%= t ".content" %></p>

app/views/static_pages/help.html.erb
<h1><%= t ".name_page" %></h1>
<p><%= t ".content" %></p>

app/views/static_pages/home.html.erb
<div class="category-featured digital">
  <% if !@hot_products.empty? %>
  <nav class="navbar nav-menu show-brand">
    <div class="navbar-brand">
      <%= link_to categories_path(is_hot: true),
      class: "brand-name" do %>
      <%= t "static_pages.home.hot_products" %>
      <% end %>
    </div>
    <div class="nav navbar-right get-more">
      <%= link_to categories_path(is_hot: true) do %>
      <%= t "static_pages.home.getmore" %>
      <% end %>
    </div>
  </nav>
  <div class="product-featured clearfix">
    <div class="row">
      <div class="col-sm-12 category-product">
        <% @hot_products.each do |product| %>
        <div class="col-sm-4">
          <div class="product-item">
            <div class="pi-img-wrapper">
              <%= image_tag product.product_image,
              class: "img-responsive" %>
              <div>
                <%= link_to product_path(product.id),
                class: "btn" do %>
                <%= t "static_pages.home.view" %>
                <% end %>
              </div>
            </div>
            <h3>
              <%= link_to product.product_name,
              product_path(product.id) %>
            </h3>
            <div class="pi-price">
              <%= t "static_pages.home.price" %>
              <%= I18n.t("product.show.product_price",
              price: "#{number_to_currency product.price_normal}") %>
            </div>
            <div class="sticker sticker-new"></div>
            <div>
              <%= render "layouts/add_cart", product: product %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
  <% @categories.each do |category| %>
  <nav class="navbar nav-menu show-brand">
    <div class="navbar-brand">
      <%= link_to categories_path(category_id: category.id) do %>
      <%= category.name %>
      <% end %>
    </div>
    <div class="nav navbar-right get-more">
      <%= link_to categories_path(category_id: category.id) do %>
      <%= t "static_pages.home.getmore" %>
      <% end %>
    </div>
  </nav>
  <div class="product-featured clearfix">
    <div class="row">
      <div class="col-sm-12 category-product">
        <% category.sub_categories.each do |sub_category| %>
        <% Product.get_limit_products(sub_category.id).each do |product| %>
        <div class="col-sm-4">
          <div class="product-item">
            <div class="pi-img-wrapper">
              <%= image_tag product.product_image,
              class: "img-responsive" %>
              <div>
                <%= link_to product_path(product.id),
                class: "btn" do %>
                <%= t "static_pages.home.view" %>
                <% end %>
              </div>
            </div>
            <h3>
              <%= link_to product.product_name,
              product_path(product.id)  %>
            </h3>
            <div class="pi-price">
              <%= t "static_pages.home.price" %>
              <%= I18n.t("product.show.product_price",
              price: "#{number_to_currency product.price_normal}") %>
            </div>
            <div class="sticker sticker-new"></div>
            <div>
              <%= render "layouts/add_cart", product: product %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>