config/routes.rb
Rails.application.routes.draw do
   namespace :admin do
    root "admin/users#index"
    resources :users
  end
  namespace :admin do
    root "admin/categories#index"
    resources :categories
  end

  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/rating", to: "ratings#update"

  get "/carts", to: "carts#index"
  get "/cart", to: "carts#show"
  post "/new_cart", to: "carts#create"
  post "/update_cart", to: "carts#update"
  delete "destroy_cart", to: "carts#destroy"

  resources :users
  resources :account_activations, only: :edit
  resources :ratings, only: :update
  resources :products
  resources :orders
  resources :categories
  resources :carts, only: :show
  resources :order_details, only: [:create, :update, :destroy]

end

app/models/order.rb
class Order < ApplicationRecord
  enum type: [ :processing, :done,:cancel]

  has_many :order_details, dependent: :destroy

  belongs_to :user

  validates :total_payment, presence: true,
    numericality: {greater_than_or_equal_to: 0}
  validates :state, presence: true, inclusion: {in: Order.types.values}
  validates :receiving_address, presence: true
  validates :receiver, presence: true

  scope :get_orders, -> (user_id, state) do
    where(user_id: user_id).where.not(state: state).order("updated_at DESC")
  end

  scope :search_by_name, -> user_name do
    Order.joins(:user).where("users.user_name LIKE '%#{user_name}%'")
  end

  scope :search_by_state, -> state do
    where(state: state).order("updated_at DESC")
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :load_order, only: [:update, :show, :destroy]
  before_action :load_orders, only: :index
  before_action :load_list_product, only: :new

  def new
    if logged_in?
      @order = Order.new
    else
      flash[:warning] = t "order.login"
      redirect_to login_path
    end
  end

  def index
  end

  def create
    @order = Order.new order_params
    products = get_orders
    result = false
    result1 = false
    if products.present?
      Order.transaction do
        result = @order.save
        result1 = save_order_details(products, @order.id)
        raise ActiveRecord::Rollback if result1 == false
      end
      if result && result1
        flash[:success] = t "order.create_success"
        session.delete(:cart)
        redirect_to orders_path(user_id: current_user.id)
      else
        get_list_products
        render :new
      end
    else
      flash[:warning] = t "order.order_not_found"
      redirect_to root_path
    end
  end

  def show
    if  @order.order_details.blank?
      flash[:warning] = t "order.order_not_found"
    end
  end

  def update
    if request.xhr?
      if admin?
        if params[:value]=="accept"
          @order.state = Order.types[:done]
          @order.save
          OrderMailer.confirm_order(User.find_by(id: @order.user_id),@order).deliver_now
          #update so luong product khi ma admin da duyet don hang
          @order.order_details.each do|order_detail|
          product=Product.find_by(id: order_detail.product_id)
          product.quanlity-=order_detail.quanlity
          product.save
         end
        elsif params[:value] == "deny"
          @order.state = Order.types[:cancel]
        end
        if @order.save
          flash[:success] = t "admin.updated"
          redirect_to orders_path
        else
          flash[:warning] = t "admin.update_failed"
          render :show
        end
      end
    end
  end

  def destroy
    if @order.destroy
      flash[:success] = t "order.delete_success"
      redirect_to orders_path
    else
      flash[:warning] = t "order.delete_failed"
      render :show
    end
  end

  private
  def load_list_product
    get_list_products
  end

  def load_order
    @order = Order.find_by id: params[:id]
    return redirect_to(orders_path) if @order.nil?
  end

  def order_params
   params.require(:order).permit :user_id, :total_payment, :receiver,
      :receiving_address, :state, :note
  end

  def load_orders
    if admin?
      load_orders_for_admin
    else
      load_orders_for_user params[:user_id], Order.types[:waiting]
    end
    if @orders.blank?
      flash[:warning] = t "order.order_not_found"
      if admin?
        redirect_to orders_path
      else
        redirect_to root_path
      end
    end
  end

  def load_orders_for_admin
    @orders = Order.order(updated_at: :desc, state: :desc)
      .paginate page: params[:page], per_page: Settings.client.number_product
    if params[:order_search].present?
      @orders = Order.search_by_name(params[:order_search])
        .paginate page: params[:page], per_page: Settings.client.number_product
    end
    if params[:state].present?
      @orders = Order.search_by_state(params[:state])
        .paginate page: params[:page], per_page: Settings.client.number_product
    end
  end

  def load_orders_for_user user_id, type
    @orders = Order.get_orders(user_id, type)
      .paginate page: params[:page], per_page: Settings.client.number_product
  end

  def save_order_details products, order_id
    result = true
    OrderDetail.transaction do
      products.each do |product|
        order_detail = new_order_detail(product, order_id)
        if !order_detail.save
          result = false
        end
      end
    end
    result
  end

  def new_order_detail product, order_id
    quanlity = product["quanlity"]
    product_id = product["product_id"]
    total_price = get_price(product_id, quanlity)
    OrderDetail.new(quanlity: quanlity, total_price: total_price,
      order_id: order_id, product_id: product_id)
  end

end

app/views/orders/_order.html.erb
<tr>
  <td>
    <%= get_index order_counter %>
  </td>
  <% if admin? %>
    <td>
      <%= order.user.user_name %>
    </td>
  <% end %>
  <td>
    <%= order.total_payment %>
  </td>
  <td>
    <%= order.updated_at %>
  </td>
  <td>
    <%= get_state order.state %>
  </td>
  <td>
    <%= link_to I18n.t("admin.detail"), order_path(order.id),
      class: "btn btn-primary" %>
  </td>
  <td>
     <%if order.state!=Order.types[:done] %>
    <%= link_to I18n.t("admin.delete"), order,
      data: {confirm: I18n.t("admin.confirm-delete")},
      method: :delete, class: "btn btn-danger" %>
    <%end%>

  </td>
</tr>

app/views/orders/_order_detail.html.erb
<tr>
  <td>
    <%=order_detail_counter+Settings.client.num_index %>
  </td>
  <td>
    <%= order_detail.product.product_name %>
  </td>
  <td>
    <%= order_detail.quanlity %>
  </td>
  <td>
    <%= order_detail.total_price %>
  </td>
</tr>

app/views/orders/_product_item.html.erb
<tr>
  <td>
    <%= get_index product_item_counter %>
  </td>
  <td>
    <%= product_item.product_name %>
  </td>
  <td>
    <%= get_quanlity(product_item.id) %>
  </td>
  <td>
    <%= get_price(product_item.id, get_quanlity(product_item.id)) %>
  </td>
</tr>

app/views/orders/index.html.erb
<h1 class="admin-title"><%= I18n.t("order.your_orders") %></h1>
<hr/>
<div class="admin-content">
  <div class="row">
    <div class="btn-new-category">
    <%= form_tag orders_path, method: "GET" do %>
      <%= select_tag :state,
        options_for_select(Order.types, params[:state]),
        include_blank: I18n.t("order.all"),
        class: "form-control", onchange: "submit()" %>
    <% end %>
    </div>
    <% if admin? %>
      <div class="btn-new-category">
        <%= form_tag orders_path(user_id: current_user.id), method: "GET" do %>
          <%= search_field_tag :order_search, params[:order_search],
            class: "form-control",
            placeholder: I18n.t("layouts.header.search_holder") %>
          <%= submit_tag I18n.t("layouts.header.search"),
            class: "btn btn-default" %>
        <% end %>
      </div>
      
    <% end -%>
  </div>
  <div class="row">
    <%= will_paginate @orders %>
    <table class="table table-bordered">
      <tr>
        <th><%= t "admin.index" %></th>
        <% if admin? %>
          <th><%= t "admin.name" %></th>
        <% end %>
        <th><%= t "admin.total_payment" %></th>
        <th><%= t "admin.date" %></th>
        <th><%= t "order.state" %></th>
        <th><%= t "admin.detail" %></th>
        <th><%= t "admin.delete" %></th>
      </tr>
      <%= render partial: "order", collection: @orders %>
    </table>
    <%= will_paginate @orders %>
  </div>
</div>

app/views/orders/new.html.erb
<h1 class="admin-title">
  <%= t "order.update_title" %>
</h1>
<hr/>
<div class="admin-content">
  <div class="row">

    <%= form_for @order do |f| %>
    <div class="col-md-6">
      <%= render "shared/error_messages", object: @order %>

      <%= f.label I18n.t("admin.name") %>
      <%= f.label :user_name, current_user.user_name,
      class: "form-control" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <br/>

      <%= f.label I18n.t("admin.receiver") %>
      <%= f.text_field :receiver, class: "form-control" %>
      <br/>

      <%= f.label I18n.t("admin.receiving_address") %>
      <%= f.text_field :receiving_address, class: "form-control" %>
      <br/>

      <%= f.label I18n.t("admin.note") %>
      <%= f.text_area :note, class: "form-control" %>
      <br/>

      <%= f.label I18n.t("admin.total_payment") %>
      <%= f.text_field :total_payment, value: get_total_payment,
      class: "form-control", readonly: true %>
      <br/>

      <%= f.hidden_field :state, value: Order.types[:processing] %>

      <button  id="done" class="btn btn-primary"><%= t("admin.complete") %></button>
    </div>
    <% end %>
    <div class="col-md-6">
      <h3>
        <%= I18n.t("order.order_details") %>
      </h3>
      <table class="table table-bordered">
        <tr>
          <th>
            <%= t "admin.index" %>
          </th>
          <th>
            <%= t "admin.name" %>
          </th>
          <th>
            <%= t "admin.quanlity" %>
          </th>
          <th>
            <%= t "admin.price" %>
          </th>
        </tr>
        <%= render partial: "product_item", collection: @products %>
        <tr>
          <td colspan="3">
            <b>
              <%= t "admin.total_payment" %>
            </b>
          </td>
          <td>
            <b>
              <%= get_total_payment %>
            </b>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-md-offset-5">
    <%= link_to I18n.t("admin.back"),carts_path,
    class: "btn btn-danger" %>
   
  </div>
</div>
<style>
 #done{  background-color:  #f44336; /* Green */
  border: none;
  color: white;
  padding: 10px 30px;
  text-align: left;
  text-decoration: none;
  display: inline-block;
  font-size: 12px;
  margin: 4px 2px;
  cursor: pointer;


  }


</style>

app/views/orders/show.html.erb
<h1 class="admin-title">
  <%= t "order.update_title" %>
</h1>
<hr/>
<div class="admin-content">
  <div class="row">

    <%= form_for @order do |f| %>
    <div class="col-md-6">
      <%= render "shared/error_messages", object: @order %>

      <%= f.label I18n.t("admin.name") %>
      <%= f.label :user_name, current_user.user_name,
      class: "form-control" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <br/>

      <%= f.label I18n.t("admin.receiver") %>
      <%= f.text_field :receiver, class: "form-control", readonly: true %>
      <br/>

      <%= f.label I18n.t("admin.receiving_address") %>
      <%= f.text_field :receiving_address, class: "form-control",
      readonly: true %>
      <br/>

      <%= f.label I18n.t("admin.note") %>
      <%= f.text_area :note, class: "form-control", readonly: true %>
      <br/>
      
      <%= f.label I18n.t("admin.total_payment") %>
      <%= f.text_field :total_payment, class: "form-control",
      readonly: true %>
      <br/>
      
      <%= f.hidden_field :state, value: Order.types[:processing] %>

      <% if @order.state == Order.types[:processing] && admin? %>
      <button onclick=accept() id="done" class="btn btn-primary"><%= t("admin.confirm") %></button>
      <button onclick=deny() id="cancel" class="btn btn-danger">Cancel</button>
      <% end -%>
    </div>
    <% end %>
    <div class="col-md-6">
      <h3>
        <%= t "order.order_details" %>
      </h3>
      <table class="table table-bordered">
        <tr>
          <th>
            <%= t "admin.index" %>
          </th>
          <th>
            <%= t "admin.name" %>
          </th>
          <th>
            <%= t "admin.quanlity" %>
          </th>
          <th>
            <%= t "admin.price" %>
          </th>
        </tr>
        <%= render partial: "order_detail", collection: @order.order_details %>
        <tr>
          <td colspan="3">
            <b>
              <%= t "admin.total_payment" %>
            </b>
          </td>
          <td>
            <b>
              <%= @order.total_payment %>
            </b>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-1 col-md-offset-5">
    <%= link_to I18n.t("admin.back"), orders_path(user_id: current_user.id),
    class: "btn btn-danger" %>
  </div>
</div>
<style>
  #cancel{
 background-color:   #555555; /* Green */
  border: none;
  color: white;
  padding: 10px 30px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 12px;
  margin: 4px 2px;
  cursor: pointer;
  }
  #done{  background-color:   #555555; /* Green */
  border: none;
  color: white;
  padding: 10px 30px;
  text-align: left;
  text-decoration: none;
  display: inline-block;
  font-size: 12px;
  margin: 4px 2px;
  cursor: pointer;


  }
</style>

  <script>
      var pageURL = $(location).attr("href");

  function accept(){
    $.ajax({
      url: pageURL,
      type: 'patch',
      data: {value: 'accept' }

    })
    $.ajax().done(function(){
      window.location.href = 'http://localhost:3000/orders?user_id=2';

    })
  }
  function deny(){
    $.ajax({
      url: pageURL,
      type: 'patch',
      data: {value: 'deny'}
    })
    $.ajax().done(function(){
      window.location.href = 'http://localhost:3000/orders?user_id=2';

    })
  }
  </script>