config/routes.rb
Rails.application.routes.draw do
   namespace :admin do
    root "admin/users#index"
    resources :users
  end
  namespace :admin do
    root "admin/categories#index"
    resources :categories
  end

  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/rating", to: "ratings#update"

  get "/carts", to: "carts#index"
  get "/cart", to: "carts#show"
  post "/new_cart", to: "carts#create"
  post "/update_cart", to: "carts#update"
  delete "destroy_cart", to: "carts#destroy"

  resources :users
  resources :account_activations, only: :edit
  resources :ratings, only: :update
  resources :products
  resources :orders
  resources :categories
  resources :carts, only: :show
  resources :order_details, only: [:create, :update, :destroy]

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    get_list_products
  end

  def create
    init_session
    product_id = params[:product_id].to_i
    quanlity = params[:quanlity].to_i
    product = {product_id: product_id, quanlity: quanlity}
    add_product_into_cart(get_orders, product)
  end

  def update
    product_id = params[:product_id].to_i
    quanlity = params[:quanlity].to_i
    product = {product_id: product_id, quanlity: quanlity}
    if !update_product_in_cart(get_orders, product)
      flash[:warning] = t "layouts.carts.update_failed"
      redirect_to carts_path
    end
    get_list_products
  end

  def show
  end

  def destroy
    product_id = params[:product_id].to_i
    if delete_product_in_cart(get_orders, product_id)
      flash[:success] = t "layouts.carts.deleted"
    else
      flash[:warning] = t "layouts.carts.delete_failed"
    end
    redirect_to carts_path
  end

end

app/views/carts/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8 col-md-6">
      <h4><%= product.product_name %></h4>
    </div>
    <div class="col-xs-4 col-md-6">
      <%= form_tag update_cart_path, remote: true do %>
        <div class="row">
          <div class="col-xs-4">
            <%= hidden_field_tag :product_id, product.id %>
            <%= number_field_tag :quanlity, get_quanlity(product.id),
              class: "form-control", min: Settings.server.min_quanlity %>
          </div>
          <div class="col-xs-4">
            <h4><span class="glyphicon glyphicon-remove"></span>
              <%= product.price_normal %>
            </h4>
          </div>
          <div class="col-xs-4 text-right">
            <h4>
              <span>
                <%= get_price(product.id, get_quanlity(product.id)) %>
              </span>
            </h4>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-4 text-right">
            <%= submit_tag I18n.t("layouts.carts.update"),
              class: "btn btn-primary" %>
          </div>
          <div class="col-xs-4 text-right">
            <%= link_to "Delete", destroy_cart_path(product_id: product.id),
              method: "delete",
              data: {confirm: I18n.t("admin.confirm-delete")},
              class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% @products.each do |product| %>
  <%= render "carts/cart_row", product: product, show_total: true %>
<% end %>

app/views/carts/_total_payment.html.erb
<h4 class="text-right"><%= t "layouts.carts.total_price" %>
  <span><%= get_total_payment %></span>
</h4>

app/views/carts/create.js.erb
$('.cart-text').html('<%= j (render 'layouts/cart_text') %>')

app/views/carts/destroy.js.erb
$('.cart-text').html('<%= j (render 'layouts/cart_text') %>')
$('.shopping-cart').html('<%= j (render 'carts/shopping_cart') %>')

app/views/carts/index.html.erb
<div class="shopping-cart">
  <% @products.each do |product| %>
    <%= render "carts/cart_row", product: product %>
  <% end %>
</div>
<div class="total_payment">
  <%= render "carts/total_payment" %>
</div>
<div class="text-right">
  <%= link_to I18n.t("order.checkout"), new_order_path,
    class: "btn btn-primary" %>
</div>

app/views/carts/update.js.erb
$('.cart-text').html('<%= j (render 'layouts/cart_text') %>')
$('.shopping-cart').html('<%= j (render 'carts/shopping_cart') %>')
$('.total_payment').html('<%= j (render 'carts/total_payment') %>')