config/routes.rb
Rails.application.routes.draw do
   namespace :admin do
    root "admin/users#index"
    resources :users
  end
  namespace :admin do
    root "admin/categories#index"
    resources :categories
  end

  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  post "/rating", to: "ratings#update"

  get "/carts", to: "carts#index"
  get "/cart", to: "carts#show"
  post "/new_cart", to: "carts#create"
  post "/update_cart", to: "carts#update"
  delete "destroy_cart", to: "carts#destroy"

  resources :users
  resources :account_activations, only: :edit
  resources :ratings, only: :update
  resources :products
  resources :orders
  resources :categories
  resources :carts, only: :show
  resources :order_details, only: [:create, :update, :destroy]

end

app/views/layouts/_add_cart.html.erb
<%= form_tag new_cart_path, remote: true do %>
  <div class="input-group">
    <%= number_field_tag :quanlity, Settings.server.min_quanlity,
      min: Settings.server.min_quanlity,max:product.quanlity, class: "form-control" %>
    <div class="input-group-btn">
      <%= hidden_field_tag :product_id, product.id %>
      <%= submit_tag I18n.t("static_pages.home.add2cart"),
        class: "btn add2cart" %>
    </div>
  </div>
<% end %>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{get_size_cart} #{I18n.t('layouts.header.cart')}
  ( #{number_to_currency get_total_payment} )", carts_path,
  class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<footer>
  <div class="footer" id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
          <h3><%= t ".about_us" %></h3>
          <ul>
            <li>
              <%= link_to "#" do %>
                <%= t ".new" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t ".customer" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t ".service" %>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
          <h3><%= t ".contact" %></h3>
          <ul>
            <li>
              <div class="input-append newsletter-box text-center">
                <input type="text" class="full text-center"
                  placeholder="Email">
                <button class="btn bg-gray" type="button"><%= t ".send" %>
                  <i class="fa fa-long-arrow-right"></i>
                </button>
              </div>
            </li>
          </ul>
          <ul class="social">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-facebook"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-twitter"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-google-plus"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-pinterest"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-youtube"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <p class="pull-left"><%= t ".cright" %></p>
      <div class="pull-right">
        <ul class="nav nav-pills payments">
          <li><i class="fa fa-cc-visa"></i></li>
          <li><i class="fa fa-cc-mastercard"></i></li>
          <li><i class="fa fa-cc-amex"></i></li>
          <li><i class="fa fa-cc-paypal"></i></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-layout">
  <div class="row">
    <div class="header-top">
      <div class="container">
        <div class="row clearfix">
          <div class="col-md-3 col-xs-12 text-center">
            <div class="logo-store">
              <%= link_to image_tag("/assets/logo-p.png"), root_path %>
            </div>
          </div>
          <div class="col-md-6 col-sm-8 col-xs-10">
            <div class="input-group">
              <%= form_tag products_path,method: "get" do %>
                <%= search_field_tag :search, params[:search],
                  class: "form-control",
                  placeholder: I18n.t("layouts.header.search_holder") %>
                <span class="input-group-btn">
                  <%= submit_tag I18n.t("layouts.header.search"),
                    name: :subsearch, class: "btn btn-default" %>
                </span>
              <% end %>
            </div>
          </div>
          <% if logged_in? %>
           
           
            <div class="col-md-3 col-sm-2 col-xs-2 btn-sign-group">
              <ul class="nav navbar-right">
                <li class="dropdown">
                  <button class="btn dropdown-toggle btn-account"
                    data-toggle="dropdown">
                    <%= t ".account" %>
                    <span class="glyphicon glyphicon-user pull-right"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to orders_path(user_id: current_user.id) do %>
                        <%= t ".order_history" %>
                        <span class="glyphicon glyphicon-cog pull-right">
                        </span>
                      <% end %>
                    </li>
                    
                    <li class="divider"></li>
                    <li>
                      <%= link_to user_path(current_user.id) do %>
                        <%= t ".profile" %>
                        <span class="glyphicon glyphicon-stats pull-right">
                        </span>
                      <% end %>
                    </li>
                    <%  if current_user.is_admin? %>

                    <li>
                      <%= link_to admin_users_path do %>
                      <%= t ".user" %>
                      <span class="glyphicon glyphicon-user pull-right">
                      </span>
                      <% end %>
                    </li>

                    <li>
                      <%= link_to new_user_path do %>
                      <%= t ".add" %>
                      <span class="glyphicon glyphicon-user pull-right">
                      </span>
                      <% end %>
                    </li>
                     <li>
                      <%= link_to admin_categories_path do %>
                      <%= t ".cate" %>
                      <span class="glyphicon glyphicon-education pull-right">
                      </span>
                      <% end %>
                    </li>
                   

                    <% end %>
                    <li>
                      <%= link_to logout_path, method: "delete" do %>
                        <%= t ".logout" %>
                        <span class="glyphicon glyphicon-log-out pull-right">
                        </span>
                      <% end %>
                    </li>
                    </ul>
                  
                </li>
              </ul>
            </div>
          <% else %>
            <div class="col-md-3 col-sm-2 col-xs-2 hidden-xs hidden-sm
              btn-sign-group">
              <ul class="nav navbar-right list-inline">
                <li>
                  <button class="btn">
                    <%= link_to signup_path do %>
                      <%= t ".sign_up" %>
                    <% end %>
                  </button>
                </li>
                <li>
                  <button class="btn">
                    <%= link_to login_path do %>
                      <%= t ".sign_in" %>
                    <% end %>
                  </button>
                </li>
              </ul>
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2 hidden-md hidden-lg
              hidden-xl btn-sign-hidden">
              <ul class="nav navbar-left">
                <li class="dropdown">
                  <button class="btn btn-primary dropdown-toggle"
                    data-toggle="dropdown">
                    <span class="glyphicon glyphicon-th-list"></span>
                  </button>
                  <ul class="dropdown-menu pull-right">
                    <div>
                      <li>
                        <%= link_to signup_path do %>
                          <span class="glyphicon glyphicon-user"></span>
                          <%= t ".sign_up" %>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to login_path do %>
                          <span class="glyphicon glyphicon-log-in"></span>
                          <%= t ".sign_in" %>
                        <% end %>
                      </li>
                    </div>
                  </ul>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="header-bottom">
      <nav class="nav navbar-custom navbar-static">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse"
            data-target=".js-navbar-collapse">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to I18n.t("layouts.header.name_of_web"), root_path,
            class: "navbar-brand"%>
        </div>
        <div class="collapse navbar-collapse js-navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to products_path do %>
                <%= t ".recent" %>
              <% end %>
            </li>
            <li>
              <%= link_to about_path do %>
                <%= t ".introduce" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t ".new" %>
              <% end %>
            </li>
            <li>
              <%= link_to help_path do %>
                <%= t ".help" %>
              <% end %>
            </li>
            <li>
              <%= link_to contact_path do %>
                <%= t ".contact" %>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-right link-cart">
            <li class="cart-text"><%= render "layouts/cart_text" %></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_navigation_menu.html.erb
<div class="nav-side-menu">
  <div class="brand">
    <%= t "layouts.navigation_menu.menu" %>
  </div>
  <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse"
    data-target="#menu-content"></i>
  <div class="menu-list">
    <ul id="menu-content" class="menu-content collapse out">
      <% $nav_categories.each do |category| %>
        <% if !category.sub_categories.empty? %>
          <li data-toggle="collapse" data-target="#<%= category.name %>"
            class="collapsed active">
            <%= link_to categories_path(category_id: category.id) do %>
              <i class="fa fa-dashboard fa-lg"></i>
              <%= category.name %>
              <span class="arrow"></span>
            <% end %>
          </li>
          <ul class="sub-menu collapse" id="<%= category.name %>">
            <% category.sub_categories.each do |sub_category| %>
              <li>
                <%= link_to categories_path(category_id: sub_category.id) do %>
                  <%= sub_category.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <li>
            <%= link_to products_path( category_id: category.id) do %>
              <i class="fa fa-dashboard fa-lg"></i>
              <%= category.name %>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<div class="filter">
  <%= form_tag products_path, method: "get" do %>
    <div class="input-group">
      <span class="input-group-addon">
        <%= I18n.t "layouts.navigation_menu.category" %>
      </span>
      <%= select_tag :category_id,
        options_from_collection_for_select($nav_categories, :id, :name),
        class: "form-control" %>
    </div>
    <div class="input-group">
      <span class="input-group-addon">
        <%= I18n.t "layouts.navigation_menu.price" %>
      </span>
      <span>
        <%= select_tag :price, options_for_select(Product::PRICE),
          class: "form-control" %>
      </span>
    </div>
    <div class="input-group">
      <span class="input-group-addon">
        <%= I18n.t "layouts.navigation_menu.rating" %>
      </span>
      <span>
        <%= select_tag :rating, options_for_select(Product::RATING),
          class: "form-control" %>
      </span>
    </div>
    <div class="input-group">
      <span class="input-group-addon">
        <%= I18n.t "layouts.navigation_menu.order" %>
      </span>
      <span>
        <%= select_tag :order, options_for_select(Product::ORDER),
          class: "form-control" %>
      </span>
    </div>
    <div class="input-group">
      <span class="input-group-addon">
        <%= I18n.t "layouts.navigation_menu.by" %>
      </span>
      <span>
        <%= select_tag :option, options_for_select(Product::OPTION),
          class: "form-control" %>
      </span>
    </div>
    <%= submit_tag  I18n.t("product.index.sort"), name: :subsearch,
      class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_slider.html.erb
<div class="first-slider">
  <div id="carousel-example-generic" class="carousel slide carousel-fade">
  <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0"
        class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <!-- Item 1 -->
      <div class="item active slide1">
        <div class="row">
          <div class="container">
            <div class="col-md-9 text-left">
              <h3 data-animation="animated bounceInDown"></h3>
              <h4 data-animation="animated bounceInUp"></h4>
            </div>
          </div>
        </div>
      </div>
      <!-- Item 2 -->
      <div class="item slide2">
        <div class="row">
          <div class="container">
            <div class="col-md-7 text-left">
              <h3 data-animation="animated bounceInDown"></h3>
              <h4 data-animation="animated bounceInUp"></h4>
            </div>
          </div>
        </div>
      </div>
      <!-- Item 3 -->
      <div class="item slide3">
        <div class="row">
          <div class="container">
            <div class="col-md-7 text-left">
              <h3 data-animation="animated bounceInDown"></h3>
              <h4 data-animation="animated bounceInUp"></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Wrapper for slides-->
    <a class="left carousel-control" href="#carousel-example-generic"
      role="button" data-slide="prev">
      <i class="fa fa-angle-left"></i>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic"
      role="button" data-slide="next">
      <i class="fa fa-angle-right"></i>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   
  <title><%= t ".title" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://cdn.bootcss.com/animate.css/3.5.1/animate.min.css">
  </head>

  <body>
    <div class="row">
      <div class="container">
        <%= render "layouts/header" %>
        <div class="row slider">
          <%= render "layouts/slider" %>
        </div>
        <div class="row page-content">
          <div class="col-md-3" id="menu-nav">
            <div class="row">
              <%= render "layouts/navigation_menu" %>
            </div>
          </div>
          <div class="col-md-9 content">
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>